// You are given two strings s and t.

// String t is generated by random shuffling string s and
// then add one more letter at a random position.

// Return the letter that was added to t.

// Example 1:
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Example 2:
// Input: s = "", t = "y"
// Output: "y"

// Example 3:
// Input: s = "a", t = "aa"
// Output: "a"

// Example 4:
// Input: s = "ae", t = "aea"
// Output: "a"

var findTheDifference = function (s, t) {
    let map = {};

    for (let sVal of s) {
        if (map[sVal]) {
            map[sVal]++;
        } else {
            map[sVal] = 1;
        }
    }

    for (let tVal of t) {
        if (!map[tVal]) {
            return tVal;
        } else {
            [tVal]--;
        }
    }
}
